version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - sonarcloud/scan:
          context: SonarCloud

workflows:
  sonar_scan:
    jobs:
      - build
